package com.wudy.locationwudy.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wudy.locationwudy.bean.MapLocationBean;

import com.wudy.locationwudy.bean.MapLocationBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mapLocationBeanDaoConfig;

    private final MapLocationBeanDao mapLocationBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mapLocationBeanDaoConfig = daoConfigMap.get(MapLocationBeanDao.class).clone();
        mapLocationBeanDaoConfig.initIdentityScope(type);

        mapLocationBeanDao = new MapLocationBeanDao(mapLocationBeanDaoConfig, this);

        registerDao(MapLocationBean.class, mapLocationBeanDao);
    }
    
    public void clear() {
        mapLocationBeanDaoConfig.clearIdentityScope();
    }

    public MapLocationBeanDao getMapLocationBeanDao() {
        return mapLocationBeanDao;
    }

}
